package com.rameysoft.main.model;

// Generated Jun 28, 2015 9:47:25 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentLines generated by hbm2java
 */
@Entity
@Table(name = "payment_lines")
public class PaymentLines implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Payment payment;
	private String checkNo;
	private Double paymentAmount;
	private Double receivedAmount;
	private Date date;
	private String paymentMode;
	private Date paymentLineDate;

	public PaymentLines() {
	}

	public PaymentLines(Payment payment, Date date) {
		this.payment = payment;
		this.date = date;
	}

	public PaymentLines(Payment payment, String checkNo,
			Double paymentAmount, Double receivedAmount, Date date,
			String paymentMode, Date paymentLineDate) {
		this.payment = payment;
		this.checkNo = checkNo;
		this.paymentAmount = paymentAmount;
		this.receivedAmount = receivedAmount;
		this.date = date;
		this.paymentMode = paymentMode;
		this.paymentLineDate = paymentLineDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, optional=false)
	@JoinColumn(name = "payment_id", nullable = false)
	public Payment getPayment() {
		return this.payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@Column(name = "check_no", length = 45)
	public String getCheckNo() {
		return this.checkNo;
	}

	public void setCheckNo(String checkNo) {
		this.checkNo = checkNo;
	}

	@Column(name = "payment_amount", precision = 22, scale = 0)
	public Double getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(Double paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "received_amount", precision = 22, scale = 0)
	public Double getReceivedAmount() {
		return this.receivedAmount;
	}

	public void setReceivedAmount(Double receivedAmount) {
		this.receivedAmount = receivedAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "payment_mode", length = 45)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_line_date", length = 19)
	public Date getPaymentLineDate() {
		return this.paymentLineDate;
	}

	public void setPaymentLineDate(Date paymentLineDate) {
		this.paymentLineDate = paymentLineDate;
	}

}
