package com.rameysoft.main.model;

// Generated Jun 28, 2015 9:47:25 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * PurchaseOrder generated by hbm2java
 */
@Entity
@Table(name = "purchase_order")
public class PurchaseOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Supplier supplier;
	private int quantity;
	private double purchasedAmount;
	private String description;
	private String type;
	private String specialIdNumber;
	private Date purchaseOrderInsertDate;
	private Date purchaseOrderUpdateDate;
	private Set<PoLines> poLineses = new HashSet<PoLines>(0);

	public PurchaseOrder() {
	}

	public PurchaseOrder(int quantity, double purchasedAmount) {
		this.quantity = quantity;
		this.purchasedAmount = purchasedAmount;
	}

	public PurchaseOrder(Supplier supplier, int quantity,
			double purchasedAmount, String description, String type,
			String specialIdNumber, Date purchaseOrderInsertDate,
			Date purchaseOrderUpdateDate, Set<PoLines> poLineses) {
		this.supplier = supplier;
		this.quantity = quantity;
		this.purchasedAmount = purchasedAmount;
		this.description = description;
		this.type = type;
		this.specialIdNumber = specialIdNumber;
		this.purchaseOrderInsertDate = purchaseOrderInsertDate;
		this.purchaseOrderUpdateDate = purchaseOrderUpdateDate;
		this.poLineses = poLineses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id")
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "purchased_amount", nullable = false, precision = 22, scale = 0)
	public double getPurchasedAmount() {
		return this.purchasedAmount;
	}

	public void setPurchasedAmount(double purchasedAmount) {
		this.purchasedAmount = purchasedAmount;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "special_id_number", length = 45)
	public String getSpecialIdNumber() {
		return this.specialIdNumber;
	}

	public void setSpecialIdNumber(String specialIdNumber) {
		this.specialIdNumber = specialIdNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchase_order_insert_date", length = 19)
	public Date getPurchaseOrderInsertDate() {
		return this.purchaseOrderInsertDate;
	}

	public void setPurchaseOrderInsertDate(Date purchaseOrderInsertDate) {
		this.purchaseOrderInsertDate = purchaseOrderInsertDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchase_order_update_date", length = 19)
	public Date getPurchaseOrderUpdateDate() {
		return this.purchaseOrderUpdateDate;
	}

	public void setPurchaseOrderUpdateDate(Date purchaseOrderUpdateDate) {
		this.purchaseOrderUpdateDate = purchaseOrderUpdateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purchaseOrder")
	@Cascade(CascadeType.ALL)
	public Set<PoLines> getPoLineses() {
		return this.poLineses;
	}

	public void setPoLineses(Set<PoLines> poLineses) {
		this.poLineses = poLineses;
	}

}
