package com.rameysoft.main.model;

// Generated Jun 28, 2015 9:47:25 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier")
public class Supplier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2413968833522643175L;
	private Integer id;
	private String name;
	private Set<PurchaseOrder> purchaseOrders = new HashSet<PurchaseOrder>(0);

	public Supplier() {
	}

	public Supplier(String name) {
		this.name = name;
	}

	public Supplier( String name, Set<PurchaseOrder> purchaseOrders) {
		this.name = name;
		this.purchaseOrders = purchaseOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.PERSIST})
	public Set<PurchaseOrder> getPurchaseOrders() {
		return this.purchaseOrders;
	}

	public void setPurchaseOrders(Set<PurchaseOrder> purchaseOrders) {
		this.purchaseOrders = purchaseOrders;
	}
	
	@Override
	public String toString() {
		return "Supplier [id=" + id + ", name=" + name + ", purchaseOrders="
				+ purchaseOrders + "]";
	}

}
